import { spawnSync } from 'node:child_process';
import { createHash } from 'node:crypto';
import {
    existsSync,
    mkdirSync,
    readFileSync,
    statSync,
    writeFileSync,
} from 'node:fs';
import net from 'node:net';
import { homedir } from 'node:os';
import { dirname, join, resolve } from 'node:path';

export const APP_NAME = 'quick-capture';
export const REGISTRY_DIR = join(homedir(), '.config', APP_NAME);
export const REGISTRY_PATH = join(REGISTRY_DIR, 'worktrees.json');

export function getRepoRoot(cwd = process.cwd()) {
  const result = spawnSync('git', ['rev-parse', '--show-toplevel'], {
    cwd,
    encoding: 'utf8',
  });
  if (result.status !== 0) {
    throw new Error('Not inside a git repository');
  }
  return result.stdout.trim();
}

export function getMainRepoRoot(cwd = process.cwd()) {
  const result = spawnSync('git', ['rev-parse', '--git-common-dir'], {
    cwd,
    encoding: 'utf8',
  });
  if (result.status !== 0) {
    throw new Error('Not inside a git repository');
  }
  return resolve(dirname(result.stdout.trim()));
}

export function getBranchName(cwd = process.cwd()) {
  const result = spawnSync('git', ['rev-parse', '--abbrev-ref', 'HEAD'], {
    cwd,
    encoding: 'utf8',
  });
  if (result.status !== 0) {
    throw new Error('Could not determine git branch');
  }
  return result.stdout.trim();
}

export function isLinkedWorktree(cwd = process.cwd()) {
  const gitPath = join(cwd, '.git');
  if (!existsSync(gitPath)) return false;
  return statSync(gitPath).isFile();
}

export function branchToSlug(branch) {
  const slug = branch
    .toLowerCase()
    .replace(/\//g, '-')
    .replace(/[^a-z0-9-]+/g, '-')
    .replace(/-+/g, '-')
    .replace(/^-|-$/g, '');
  return slug.slice(0, 63) || 'worktree';
}

export function slugToComposeProject(slug) {
  return `qc-${slug}`;
}

function crc32(input) {
  const hash = createHash('md5').update(input).digest();
  return hash.readUInt32BE(0);
}

export function defaultPortBlockIndex(slug) {
  return crc32(slug) % 50;
}

export function portsForBlockIndex(index) {
  const blockBase = 3000 + index * 10;
  return {
    api: blockBase,
    web: blockBase + 1,
    whisper: blockBase + 2,
  };
}

export function defaultPortsForSlug(slug) {
  return portsForBlockIndex(defaultPortBlockIndex(slug));
}

export function isPortAvailable(port) {
  return new Promise((resolvePromise) => {
    const server = net.createServer();
    server.unref();
    server.on('error', () => resolvePromise(false));
    server.listen({ port, host: '127.0.0.1' }, () => {
      server.close(() => resolvePromise(true));
    });
  });
}

export async function allocatePorts(slug, reservedPorts = []) {
  const reserved = new Set(reservedPorts);
  const start = defaultPortBlockIndex(slug);

  for (let offset = 0; offset < 50; offset += 1) {
    const index = (start + offset) % 50;
    const ports = portsForBlockIndex(index);
    const portValues = [ports.api, ports.web, ports.whisper];
    if (portValues.some((port) => reserved.has(port))) continue;

    const available = await Promise.all(portValues.map((port) => isPortAvailable(port)));
    if (available.every(Boolean)) {
      return { ports, blockIndex: index };
    }
  }

  throw new Error('Could not find an available port block (all 50 blocks in use)');
}

export function readRegistry() {
  if (!existsSync(REGISTRY_PATH)) {
    return { worktrees: [] };
  }
  try {
    return JSON.parse(readFileSync(REGISTRY_PATH, 'utf8'));
  } catch {
    return { worktrees: [] };
  }
}

export function writeRegistry(registry) {
  mkdirSync(REGISTRY_DIR, { recursive: true });
  writeFileSync(REGISTRY_PATH, `${JSON.stringify(registry, null, 2)}\n`, 'utf8');
}

export function getRegistryEntry(registry, worktreePath) {
  const normalized = worktreePath.replace(/\/$/, '');
  return registry.worktrees.find((entry) => entry.path.replace(/\/$/, '') === normalized);
}

export function reservedPortsFromRegistry(registry, exceptPath = null) {
  const except = exceptPath?.replace(/\/$/, '');
  const ports = [];
  for (const entry of registry.worktrees) {
    if (except && entry.path.replace(/\/$/, '') === except) continue;
    ports.push(entry.ports.api, entry.ports.web, entry.ports.whisper);
  }
  return ports;
}

export function parseEnvFile(filePath) {
  if (!existsSync(filePath)) return {};
  const env = {};
  for (const line of readFileSync(filePath, 'utf8').split('\n')) {
    const trimmed = line.trim();
    if (!trimmed || trimmed.startsWith('#')) continue;
    const eq = trimmed.indexOf('=');
    if (eq === -1) continue;
    const key = trimmed.slice(0, eq).trim();
    let value = trimmed.slice(eq + 1).trim();
    if (
      (value.startsWith('"') && value.endsWith('"')) ||
      (value.startsWith("'") && value.endsWith("'"))
    ) {
      value = value.slice(1, -1);
    }
    env[key] = value;
  }
  return env;
}

export function serializeEnvFile(env) {
  const lines = [
    '# Generated by npm run worktree:bootstrap — do not commit.',
    '',
  ];
  for (const [key, value] of Object.entries(env)) {
    if (value === undefined || value === '') continue;
    const escaped =
      value.includes(' ') || value.includes('#') ? `"${value.replace(/"/g, '\\"')}"` : value;
    lines.push(`${key}=${escaped}`);
  }
  lines.push('');
  return lines.join('\n');
}

export function buildWorktreeUrls(slug, ports, usePortless = true) {
  if (usePortless) {
    return {
      web: `https://${slug}.${APP_NAME}.localhost`,
      api: `https://api.${slug}.${APP_NAME}.localhost`,
    };
  }
  return {
    web: `https://localhost:${ports.web}`,
    api: `http://localhost:${ports.api}`,
  };
}

export function buildCorsOrigins(urls, ports) {
  const origins = new Set([
    urls.web,
    urls.api,
    `http://localhost:${ports.web}`,
    `https://localhost:${ports.web}`,
    `http://localhost:${ports.api}`,
    'http://localhost:8081',
  ]);
  return [...origins].join(',');
}

export function commandExists(command) {
  const result = spawnSync('sh', ['-c', `command -v ${command}`], { encoding: 'utf8' });
  return result.status === 0;
}

export function runNeonctl(args, cwd) {
  return spawnSync('neonctl', args, { cwd, encoding: 'utf8' });
}

export function dockerCompose(args, repoRoot) {
  const envFile = join(repoRoot, '.env.worktree');
  if (!existsSync(envFile)) {
    throw new Error('Missing .env.worktree — run npm run worktree:bootstrap first');
  }

  return spawnSync(
    'docker',
    [
      'compose',
      '-f',
      'docker-compose.yml',
      '-f',
      'docker-compose.worktree.yml',
      '--env-file',
      '.env.worktree',
      ...args,
    ],
    {
      cwd: repoRoot,
      stdio: 'inherit',
      env: process.env,
    }
  );
}

export function printWorktreeSummary(entry) {
  console.log('');
  console.log('Worktree ready');
  console.log('─'.repeat(40));
  console.log(`Branch:    ${entry.branch}`);
  console.log(`Slug:      ${entry.slug}`);
  console.log(`Path:      ${entry.path}`);
  console.log(`Neon:      ${entry.neonBranchName}`);
  console.log(`Compose:   ${entry.composeProject}`);
  console.log(`Ports:     API ${entry.ports.api} | Web ${entry.ports.web} | Whisper ${entry.ports.whisper}`);
  console.log(`Web:       ${entry.urls.web}`);
  console.log(`API:       ${entry.urls.api}`);
  console.log('');
  console.log('Start stack:  npm run docker:dev:worktree');
  console.log('Stop stack:   npm run docker:down:worktree');
  console.log('');
}
